concurrent = 1
check_interval = 0

[[runners]]
name = "gitlab-runner"
url = "https://gitlab.com/"
token = "GR1348941oSZ22pVYrPJhGNRzyvdY"
executor = "docker"
[runners.docker]
tls_verify = false
image = "docker:20.10-dind"
pull_policy = "if-not-present"
disable_cache = false
privileged = true
volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache", "/builds:/builds"]
shm_size = 0
[runners.cache]
insecure = false